# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ifelseCNum <- function(test, yes, no) {
    .Call('ojUtils_ifelseCNum', PACKAGE = 'ojUtils', test, yes, no)
}

ifelseCLogic <- function(test, yes, no) {
    .Call('ojUtils_ifelseCLogic', PACKAGE = 'ojUtils', test, yes, no)
}

ifelseCInt <- function(test, yes, no) {
    .Call('ojUtils_ifelseCInt', PACKAGE = 'ojUtils', test, yes, no)
}

ifelseCChar <- function(test, yes, no) {
    .Call('ojUtils_ifelseCChar', PACKAGE = 'ojUtils', test, yes, no)
}

