# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

internal_combn_C <- function(x) {
    .Call('_ojUtils_internal_combn_C', PACKAGE = 'ojUtils', x)
}

ifelseCNum <- function(test, yes, no) {
    .Call('_ojUtils_ifelseCNum', PACKAGE = 'ojUtils', test, yes, no)
}

ifelseCLogic <- function(test, yes, no) {
    .Call('_ojUtils_ifelseCLogic', PACKAGE = 'ojUtils', test, yes, no)
}

ifelseCInt <- function(test, yes, no) {
    .Call('_ojUtils_ifelseCInt', PACKAGE = 'ojUtils', test, yes, no)
}

ifelseCChar <- function(test, yes, no) {
    .Call('_ojUtils_ifelseCChar', PACKAGE = 'ojUtils', test, yes, no)
<<<<<<< HEAD
}

seqC <- function(x, y, by) {
    .Call('_ojUtils_seqC', PACKAGE = 'ojUtils', x, y, by)
}

triang2cf_C <- function(triang) {
    .Call('_ojUtils_triang2cf_C', PACKAGE = 'ojUtils', triang)
=======
>>>>>>> 14c99d44ca7f028e9a6d72253754dc51532607c6
}

