# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

internal_combn_C <- function(x) {
    .Call('_ojUtils_internal_combn_C', PACKAGE = 'ojUtils', x)
}

ifelseCNum <- function(test, yes, no) {
    .Call('_ojUtils_ifelseCNum', PACKAGE = 'ojUtils', test, yes, no)
}

ifelseCLogic <- function(test, yes, no) {
    .Call('_ojUtils_ifelseCLogic', PACKAGE = 'ojUtils', test, yes, no)
}

ifelseCInt <- function(test, yes, no) {
    .Call('_ojUtils_ifelseCInt', PACKAGE = 'ojUtils', test, yes, no)
}

ifelseCChar <- function(test, yes, no) {
    .Call('_ojUtils_ifelseCChar', PACKAGE = 'ojUtils', test, yes, no)
}

